default_context:
  project_name: 'businesscase'
  project_slug: 'businesscase'
  domain_main: 'businesscase.com'
  domain_staging: 'stag.businesscase.com'
  docker_swarm_stack_name_main: 'businesscase-com'
  docker_swarm_stack_name_staging: 'stag-businesscase-com'
  secret_key: 'f8558bdf6029259067eac07e4886281598889ad5765e605d8790be72e854879f'
  first_superuser: 'admin'
  first_superuser_password: 'admin'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.businesscase.com", "https://stag.businesscase.com", "https://businesscase.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@businesscase.com'
  postgres_password: 'admin'
  pgadmin_default_user: 'admin'
  pgadmin_default_user_password: 'admin'
  traefik_constraint_tag: 'businesscase.com'
  traefik_constraint_tag_staging: 'stag.businesscase.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:admin'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
